name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install Python dependencies
        run: uv sync --locked --all-extras --dev

      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install Node dependencies
        run: pnpm install

      - name: Get latest Washington PBF version
        id: get-pbf-url
        run: |
          PBF_HASH=(curl -I -s -o /dev/null -w '%header{location}' https://download.geofabrik.de/north-america/us/washington-latest.osm.pbf | sha256)
          echo "pbf-hash=$PBF_HASH" >> $GITHUB_OUTPUT

      - name: Cache GeoJSON tiles
        id: cache-tiles
        uses: actions/cache@v5
        with:
          path: static/tiles
          key: tiles-${{ steps.get-pbf-url.outputs.pbf-hash }}

      - name: Build routing tiles
        if: steps.cache-tiles.outputs.cache-hit != 'true'
        run: ./tools/build-graph.sh

      - name: build
        run: pnpm build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          path: "build/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
